version: '3.7'

services:
  shell:
    build:
      context: .
      dockerfile: ./Dockerfile-local
    container_name: shell
    command: bash -c "tail -f /dev/null"
    volumes:
      - .:/home/app
      - node_modules:/home/app/node_modules
    environment:
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'

  client:
    build:
      context: .
      dockerfile: ./Dockerfile-local
    container_name: client
    command: bash -c "npm run start:client"
    volumes:
      - .:/home/app
      - node_modules:/home/app/node_modules
    environment:
      AWS_ACCESS_KEY_ID: S3RVER
      AWS_SECRET_ACCESS_KEY: S3RVER
    ports:
      - '1234:1234'

  public:
    build:
      context: .
      dockerfile: ./Dockerfile-local
    container_name: public
    command: bash -c "npm run start:public"
    environment:
      AWS_ACCESS_KEY_ID: S3RVER
      AWS_SECRET_ACCESS_KEY: S3RVER
    ports:
      - '5678:5678'
    volumes:
      - .:/home/app
      - node_modules:/home/app/node_modules

  api:
    build:
      context: .
      dockerfile: ./Dockerfile-local
    container_name: api
    command: bash -c "npm run start:api:docker"
    environment:
      AWS_ACCESS_KEY_ID: S3RVER
      AWS_SECRET_ACCESS_KEY: S3RVER
      ELASTICSEARCH_ENDPOINT: http://elasticsearch:9200
      ELASTICSEARCH_HOST: elasticsearch
    ports:
      - '3011:3011'
      - '4000:4000'
      - '5000:5000'
      - '9000:9000'
    volumes:
      - .:/home/app
      - node_modules:/home/app/node_modules
    depends_on:
      - dynamodb-local
      - elasticsearch

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - '8000:8000'

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - '8001:8001'
    environment:
      DYNAMO_ENDPOINT: 'http://dynamodb-local:8000'
      AWS_REGION: 'us-east-1'
      AWS_ACCESS_KEY_ID: S3RVER
      AWS_SECRET_ACCESS_KEY: S3RVER
    depends_on:
      - dynamodb-local

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch:/usr/share/elasticsearch/data:z
    ports:
      - '9200:9200'
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node

volumes:
  node_modules:
  elasticsearch:
