service: ef-cms
plugins:
  - serverless-dynamodb-local
  - serverless-s3-local
  - serverless-domain-manager
  - serverless-plugin-bind-deployment-id
  - serverless-aws-documentation
  - serverless-plugin-aws-alerts
  - serverless-offline
  - serverless-plugin-git-variables
custom:
  s3:
    host: 0.0.0.0
    port: 9000
    directory: /tmp
    cors: cors-policy.xml
  dynamodb:
    start:
      inMemory: true
      migrate: true
      port: 8000
      seed: false
    # seed:
    #   test:
    #     sources:
    #     - table: ${self:provider.environment.DOCUMENTS_DYNAMODB_TABLE}
    #       sources:
    #         - ./spec/fixtures/stuff.json

  alerts:
    stages:
      - dev
      - stg
      - prod
    dashboards: true
    alarms:
      - functionThrottles
      - functionErrors
      - functionInvocations
      - functionDuration
  documentation:
    api:
      info:
        title: EF-CMS Documents API
        description: Documents API for U.S. Tax Court EF-CMS
        contact:
          url: https://www.ustaxcourt.gov
          email: webmaster@ustaxcourt.gov
        license:
          name: Creative Commons 0
          url: https://creativecommons.org/share-your-work/public-domain/cc0/
      tags:
        - name: ef-cms
          description: EF-CMS
        - name: documents
          description: rawDocument service
    summary: 'EF-CMS Documents API'
    version: '${opt:stage}-${git:sha1}'
    description: 'EF-CMS Documents API documented with OpenAPI specification'
    resources:
      - path: 'v1/documents'
        description: 'Path used for creating a rawDocument.'
      - path: 'v1/documents/{documentId}'
        description: 'Path used for retrieving rawDocument with a documentId.'
      - path: 'v1/documents/uploadPolicy'
        description: 'Path used for retrieving pre-signed policy url.'
      - path: 'v1/cases'
        description: 'Path used for creating a case.'
    models:
      - name: 'case'
        description: 'a case response'
        contentType: 'application/json'
        schema:
          type: object
          properties:
            caseId:
              type: string
              description: id of case
            userId:
              type: string
              description: id of user who created the case
            documents:
              type: array
              items:
                type: object
                properties:
                  documentId:
                    type: string
                  documentType:
                    type: string
              description: array of rawDocument ids and types associated with the case
            createdAt:
              type: string
              description: date case created
      - name: 'rawDocument'
        description: 'a rawDocument response'
        contentType: 'application/json'
        schema:
          type: object
          properties:
            documentId:
              type: string
              description: id of rawDocument
            userId:
              type: string
              description: id of user who created the rawDocument
            documentType:
              type: string
              description: type of this rawDocument
            createdAt:
              type: string
              description: date rawDocument created
      - name: 'policyUrl'
        description: 'a policy url response'
        contentType: 'application/json'
        schema:
          type: object
          properties:
            url:
              type: string
              description: url
            fields:
              $ref: '{{model: fields}}'
      - name: 'fields'
        description: 'a policy url response'
        contentType: 'application/json'
        schema:
          type: object
          properties:
            bucket:
              type: string
              description: The bucket name.
            X-Amz-Algorithm:
              type: string
              description: The algorithm.
            X-Amz-Credential:
              type: string
              description: The credential.
            X-Amz-Date:
              type: string
              description: The date.
            X-Amz-Security-Token:
              type: string
              description: The security token.
            Policy:
              type: string
              description: The policy.
            X-Amz-Signature:
              type: string
              description: The signature.
      - name: 'awsError'
        description: 'an aws internal server error, usually with status code 502 (bad gateway)'
        contentType: 'application/json'
        schema:
          type: object
          properties:
            message:
              type: string
          required:
            - message
      - name: 'unprocessableEntityError'
        description: 'a unprocessable entity error (422), due to a problem in the body or the id in the url'
        contentType: 'application/json'
        schema:
          type: object
          properties:
            message:
              type: string
          required:
            - message

  customDomain:
    domainName: efcms-${self:provider.stage}.${opt:domain}
    basePath: ''
    endpointType: 'regional'
    certificateName: efcms-${self:provider.stage}.${opt:domain}
    certificateRegion: ${opt:region}
    stage: ${self:provider.stage}
    createRoute53Record: false
    enabled: true
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  vars: ${file(./config/${self:custom.stage}.yml)}

provider:
  name: aws
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  runtime: nodejs8.10
  memorySize: 128
  timeout: 10
  logRetentionInDays: 7
  s3Endpoint: s3.${opt:region}.amazonaws.com
  dynamodbEndpoint: dynamodb.${opt:region}.amazonaws.com
  masterRegion: us-east-1
  masterDynamodbEndpoint: dynamodb.us-east-1.amazonaws.com
  deploymentBucket:
    name: ${env:SLS_DEPLOYMENT_BUCKET}
    serverSideEncryption: AES256

  environment:
    S3_ENDPOINT: ${self:custom.vars.s3Endpoint, self:provider.s3Endpoint}
    DOCUMENTS_BUCKET_NAME: ${opt:domain}-documents-${opt:stage}-${opt:region}
    DYNAMODB_ENDPOINT: ${self:custom.vars.dynamodbEndpoint, self:provider.dynamodbEndpoint}
    MASTER_DYNAMODB_ENDPOINT: ${self:custom.vars.masterDynamodbEndpoint, self:provider.masterDynamodbEndpoint}
    MASTER_REGION: ${self:custom.vars.masterRegion, self:provider.masterRegion}
    STAGE: ${self:custom.stage}

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - Ref: DocumentsBucket
            - '/*'
    - Effect: 'Allow'
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - arn:aws:dynamodb:${opt:region}:${opt:accountId}:table/${opt:casesTableName}
        - arn:aws:dynamodb:${opt:region}:${opt:accountId}:table/${opt:casesTableName}/index/*
        - arn:aws:dynamodb:${opt:region}:${opt:accountId}:table/${opt:documentsTableName}
        - arn:aws:dynamodb:${opt:region}:${opt:accountId}:table/${opt:documentsTableName}/index/*

package:
  exclude:
    - ./**
  include:
    - src/**
    - swagger.json
    - ./package.json
    - ./node_modules/**

  excludeDevDependencies: true

resources:
  Resources:
    #####
    # Begin S3
    #####
    DocumentsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.DOCUMENTS_BUCKET_NAME}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - Authorization
              AllowedMethods:
                - GET
                - POST
              AllowedOrigins:
                - '*'
              MaxAge: 3000
        VersioningConfiguration:
          Status: Enabled

    #####
    # Begin Stage for API Gateway Logging
    #####
    ApiGatewayStage:
      Type: AWS::ApiGateway::Stage
      Properties:
        DeploymentId:
          Ref: __deployment__
        RestApiId:
          Ref: ApiGatewayRestApi
        StageName: ${opt:stage}
        MethodSettings:
          - DataTraceEnabled: true
            HttpMethod: '*'
            LoggingLevel: INFO
            ResourcePath: '/*'
            MetricsEnabled: true

functions:
  createPolicyUrl:
    handler: src/documents/createPolicyUrl.create
    events:
      - http:
          path: v1/documents/uploadPolicy
          method: get
          cors: true
          documentation:
            summary: create a pre-signed url for uploads
            tags:
              - documents
            description: >
              Create a pre-signed url for rawDocument uploads to S3.
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: 'pre-signed policy upload url'
                responseModels:
                  'application/json': 'policyUrl'

  downloadPolicyUrl:
    handler: src/documents/downloadPolicyUrl.get
    events:
      - http:
          path: v1/documents/{documentId}/downloadPolicy
          method: get
          cors: true
          documentation:
            summary: create a pre-signed url for downloads
            tags:
              - documents
            description: >
              Create a pre-signed url for rawDocument downloads from S3.
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: 'pre-signed policy download url'
                responseModels:
                  'application/json': 'policyUrl'

  createDocument:
    handler: src/documents/createDocument.create
    events:
      - http:
          path: v1/documents
          method: post
          cors: true
          documentation:
            summary: create a rawDocument
            tags:
              - documents
            description: >
              Create a rawDocument.
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: 'rawDocument meta-data'
                responseModels:
                  'application/json': rawDocument

  updateCase:
    handler: src/cases/updateCase.put
    events:
      - http:
          path: v1/cases/{caseId}
          method: put
          cors: true
          documentation:
            summary: update a case
            tags:
              - cases
            description: >
              Update a case.
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: 'updated case'
                responseModels:
                  'application/json': case
              - statusCode: '422'
                responseModels:
                  'application/json': 'unprocessableEntityError'

  createCase:
    handler: src/cases/createCase.create
    events:
      - http:
          path: v1/cases
          method: post
          cors: true
          documentation:
            summary: create a case
            tags:
              - cases
            description: >
              Create a case.
            parameters:
              - name: documents
                in: body
                required: true
                description: rawDocument metadata
                schema:
                  type: array
                  items:
                    $ref: documents
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: 'case'
                responseModels:
                  'application/json': case

  getCases:
    handler: src/cases/getCases.get
    events:
      - http:
          path: v1/cases
          method: get
          cors: true
          documentation:
            summary: get all cases for a user
            tags:
              - cases
            description: >
              Get all cases for a user.
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: 'array of cases'
                responseModels:
                  'application/json': case

  getCase:
    handler: src/cases/getCase.get
    events:
      - http:
          path: v1/cases/{caseId}
          method: get
          request:
            parameters:
              paths:
                caseId: true
          cors: true
          documentation:
            summary: get a case by caseId
            tags:
              - cases
            description: >
              Get a case by caseId.
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: 'a case'
                responseModels:
                  'application/json': case

  swagger:
    handler: src/swagger/swagger.handler
    events:
      - http:
          path: v1/swagger
          method: get
          cors: true
