name: Node.js CI - Client

on:
  pull_request:
  push:
    branches:
      - dependency-updates
      - 9803-bug

jobs:
  Client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: NPM Install
        run: npm ci --legacy-peer-dep
      - name: Test Client Unit
        run: npm run test:client:unit
