name: Node.js Client Integration Tests

on:
  pull_request:
  push:
    branches:
      - flakey-tests

jobs:
  client_integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [12]
        ci_node_index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    env:
      CI: true
      CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
      CI_NODE_INDEX: ${{ matrix.ci_node_index }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 7.10.2
          security-enabled: false
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v2.0.1
        with:
          port: 8000
          cors: '*'
      - name: Web Client - Integration Tests
        run: |
          npm ci
          mkdir -p /tmp/web-client
          npm run start:api:ci > /tmp/web-client/server-output.txt &
          ./wait-for-dynamo.sh
          URL=http://localhost:4000/api/swagger ./wait-until.sh
          URL=http://localhost:9200/efcms-case ./wait-until.sh
          URL=http://localhost:9200/efcms-case-deadline ./wait-until.sh
          URL=http://localhost:9200/efcms-docket-entry ./wait-until.sh
          URL=http://localhost:9200/efcms-user ./wait-until.sh
          URL=http://localhost:9200/efcms-message ./wait-until.sh
          URL=http://localhost:9200/efcms-work-item ./wait-until.sh
          URL=http://localhost:9000/ ./wait-until.sh
          export TESTFILES=$(node split-tests.js)
          npm run test:client:integration:ci
      - name: Store Video Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: server log output
          path: /tmp/web-client/server-output.txt
