name: Node.js CI - Client Unit Tests

on:
  pull_request:
  push:
    branches:
      - flakey-tests

jobs:
  Client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Node Dependencies
        run: npm ci
      - name: Test Client Unit
        run: npm run test:client:unit
