name: E2E Cypress Public

on:
  pull_request:

jobs:
  e2e_cypress_public:
    runs-on: ubuntu-latest

    env:
      CI: true
      CHECK_DEPLOY_DATE_INTERVAL: 5000
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'
      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 7.10.2
          security-enabled: false
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v3.0.0
        with:
          port: 8000
          cors: '*'
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v1
        with:
          comment_on_pr: false
      - name: Install Node Dependencies
        run: npm ci
      - name: Run E2E Cypress
        run: |
          mkdir -p /tmp/cypress/
          npm run start:all:ci >> /tmp/cypress/cypress-output.txt &
          ./wait-until-services.sh
          sleep 5
          npm run cypress:integration:public
      - name: Store Cypress Failure Videos
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: ${{ github.workspace }}/cypress/cypress-integration/videos
