name: E2E Cypress

on:
  pull_request:

jobs:
  e2e_cypress:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [2]
        ci_node_index: [0, 1]

    env:
      CI: true
      CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
      CI_NODE_INDEX: ${{ matrix.ci_node_index }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 7.10.2
          security-enabled: false
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v3.0.0
        with:
          port: 8000
          cors: '*'
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v2
        with:
          comment_on_pr: false
      - name: Install Node Dependencies
        run: npm ci
      - name: Run E2E Cypress
        run: |
          mkdir -p /tmp/cypress/
          npm run start:all:ci >> /tmp/cypress/cypress-output.txt &
          ./wait-until-services.sh
          sleep 5
          export TESTFILES=$(npx ts-node split-tests-cypress.ts)
          npm run cypress:integration:file $TESTFILES
      - name: Move Videos
        if: always()
        run: |
          mkdir -p cypress/cypress-integration/videos-${{ matrix.ci_node_index }}/
          cp cypress/cypress-integration/videos/* cypress/cypress-integration/videos-${{ matrix.ci_node_index }}/
          ls cypress/cypress-integration/
          ls cypress/cypress-integration/videos/
          ls cypress/cypress-integration/videos-${{ matrix.ci_node_index }}
      - name: Store Cypress Failure Videos
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos-${{ matrix.ci_node_index }}
          path: ${{ github.workspace }}/cypress/cypress-integration/videos-${{ matrix.ci_node_index }}
