name: E2E Cypress Public

on:
  pull_request:

jobs:
  e2e_cypress_public:
    runs-on: ubuntu-latest

    env:
      CI: true
      CHECK_DEPLOY_DATE_INTERVAL: 5000
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: example
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'
      - name: Setup OpenSearch
        uses: ankane/setup-opensearch@v1
        with:
          opensearch-version: 2.11
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v4.0.0
        with:
          port: 8000
          cors: '*'
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v2
        with:
          comment_on_pr: false
      - name: Install Node Dependencies
        run: npm ci
      - name: Setup Postgres
        run: |
          npm run migration:postgres
          npm run seed:postgres
      - name: Run E2E Cypress
        run: |
          mkdir -p /tmp/cypress/
          npm run start:all:ci >> /tmp/cypress/cypress-output.txt &
          ./wait-until-services.sh
          sleep 5
          npm run cypress:integration:public
      - name: Store Cypress Failure Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: ${{ github.workspace }}/cypress/local-only/videos
