name: Verify PDFS

on:
  pull_request:
  push:
    branches:
      - dependency-updates

jobs:
  test_pdfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -o Acquire::Retries=3 -y graphicsmagick ghostscript
          npm ci && npm rebuild
      - name: Generate and Test PDFs
        run: npm run test:document-generation
