# name: Node.js CI - scripts

# on:
#   pull_request:
#   push:
#     branches:
#       - dependency-updates

# jobs:
#   Scripts:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v3
#         with:
#           node-version: '16'
#       - name: Scripts
#         run: |
#           npm ci
#           npm run test:scripts
